from enum import Enum


class Genre(Enum):
    ACTION = "Action"
    ADVENTURE = "Adventure"
    CARD = "Card"
    CASUAL = "Casual"
    FANTASY = "Fantasy"
    FIGHTING = "Fighting"
    HORROR = "Horror"
    INDIE = "Indie"
    METROIDVANIA = "Metroidvania"
    MMORPG = "MMORPG"
    OPEN_WORLD = "Open World"
    PARTY = "Party"
    PLATFORMER = "Platformer"
    PUZZLE = "Puzzle"
    RACING = "Racing"
    ROGUE_LIKE = "Rogue-like"
    RPG = "RPG"
    SANDBOX = "Sandbox"
    SCI_FI = "Sci-Fi"
    SHOOTER = "Shooter"
    SIMULATION = "Simulation"
    SPORTS = "Sports"
    STEALTH = "Stealth"
    STRATEGY = "Strategy"
    SURVIVAL = "Survival"
